### ISSUE TITLE
Script to Process JSON Translations

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#109]
After discussion on 2015-10-26, this is being modified to be much simpler in the near term.  We need a script that can take JSON content (formatted like we have it in the uW catalog), and import it into a language namespace on Door43.  For example, something that looks like that https://api.unfoldingword.org/obs/txt/1/am/obs-am.json should be importable to https://door43.org/am/obs.

This needs to work for:
- [x] OBS
- [x] OBS tN
- [x] OBS tQ
- [x] OBS tW

Relates to #195

**Comment by Aarontse** [comment]
Not fully understood the requirement, please elaborate more. Thanks. Aaron

**Comment by alerque** [comment]
The requirement here makes sense to be, but this seems predicated on their being an API at all. The thing being labeled that now is a static set of files being generated as if they were being pushed to a CDN. Am I missing something or is there actually no programmatic interface to the application going on here yet at all? Related discussion came up in [Slack chat just now](https://team43.slack.com/archives/general/p1436946179000429). Am I completely missing something or does is this issue one of many things that actually needs an API to build on?

**Comment by jag3773** [comment]
Effectively, this will need to be a DW plugin that accepts JSON objects that are formatted in the same way they are on the uW API, and should be able to put them into the correct location in Door43.

The example use case here is that someone will download content from our API (like https://api.unfoldingword.org/obs/txt/1/en/kt-en.json or https://api.unfoldingword.org/obs/txt/1/en/obs-en.json), run it through their translation software and then need to upload it to Door43.  The utility described here will need to be able to accept their upload, convert it to DokuWiki syntax, and put it into the correct location in Door43.

This will run on the door43.org domain.

**Comment by richmahn** [comment]
From @Aarontse on Slack:

aaron.tse [7:13 PM] 
So my understanding there are two part for this item. A: check the JSON input from the user if its compliance with the Door43 and [convert it to DokuWiki syntax]. B: Save the checked and converted document to the collect location base on the content in the document.

I think I can gather enough info from the field within the JOSN to work out the location for the doc. So part B is clear.

However for part A: 
1. I am not sure if there is any official definition for Door43 JSON (what field/key is a must or what is option..... my question is how to work out if the doc is acceptable?
2. since the user download the original doc [stage 1] from our the Door43, so it should be in DokuWiki syntax. then as Jesse said: ' the user may run it through their translation software.' so the doc may change and modified here [stage 2], and after that  need to upload it to Door43. doc in stage 2 may NOT be compliance with Door43, so it may need some fix  [the conversion]........

my questions are: Q1. is there an document on the DokuWiki syntax requirement for the Door43?  Q2. Is there any sample [stage 2] doc which need to be convert into DokuWiki syntax? may be we need to made up or chose one of this doc to be used as our base for the development.

**Comment by codemis** [comment]
@jag3773 I think we will need to talk through this issue.  I have several questions regarding the JSON format, and how a user will submit that content.  Let me know when your free to talk about it.

**Comment by jag3773** [comment]
Make sure to import tQ for Indonesian when this script is done.

**Comment by richmahn** [comment]
have all 4 done... files are tools/obs/json/json_*_import.py

**Comment by richmahn** [comment]
@jag3773 I did the import of Indonesian tQ which was successful: https://door43.org/id/obs/notes/questions/home
