### ISSUE TITLE
the git merge plugin should automatically create stubs for new language projects

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/Door43#114]
When someone submits a translation from translationStudio for a language that does not already have content on door43.org the plugin should automatically create some empty placeholder pages so that users can handle merges for those languages.

> Note: the submitted translation will not be accepted by default, but will be presented as a possible merge into the empty placeholder content.

**Comment by jag3773** [comment]
The languages will all exist, but the project for that language may not.  For example /aaa/ exists, but /aaa/obs may not exist.  If the project does not exist then it should be configured based on the tS upload.  There is an initial configuration plugin for OBS at https://github.com/unfoldingWord-dev/dokuwiki-plugin-obs.  The goal here would be to do a similar procedure but seed it based on the tS uploaded content rather than an existing level 3 source text.

**Comment by jag3773** [comment]
Related to #199
