### ISSUE TITLE
PDF for OBS fa

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#152]
We need to generate the PDF for OBS Farsi and put it into the catalog.

**Comment by jag3773** [comment]
The command to do this is
`obs/book/pdf_export.sh -l fa -c 1 -v 4.1 -o /tmp/ -r /tmp/`.

For some reason this is failing.

**Comment by alerque** [comment]
I'm not at a computer where I can test this right now, but can you give any details about _where_ in the process this is bombing out? Adding the `-d` flag should give you some debug information including a play by play of shell commands that get executed. That might have clues about where the trouble is.

**Comment by jag3773** [comment]
PDF generation is working now, but the font is not coming through at all.  Likely due to the need for a correct obs/tex/noto-fa.tex file.

**Comment by alerque** [comment]
When you say "not coming through at all" do you get pure white space or block boxes or what? If you have even partial text or boxes can you tell if it's properly showing RTL paragraph layout?

**Comment by jag3773** [comment]
At most, slight | like characters.  Mostly white space.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by richmahn** [comment]
I'm not seeing |-like characters, but blank with dots here and there (I assume they use the common period, but it looks a little bigger, darker and square, so maybe not)

**Comment by richmahn** [comment]
It's interesting that the TOC for the PDF in Acrobat Reader properly shows Farsi, from what I know of the language. But the text on each page is not showing up right.

**Comment by alerque** [comment]
@richmahn That's not surprising given the way PDF data is encoded and the font rendering stack differences between the Reader UI sidebar and the canvas space.

I don't have very long today but I am at a computer where I can try some things and will try to poke this in a couple hours. @jag3773 if you have any commits not in the main repo can you post them to a branch somewhere so I can work off of youl latest progress?

**Comment by richmahn** [comment]
@alerque Thanks. Let me know what you find. I was asking if Jesse made changes to the code, it sounds like if he did, he committed them (haven't looked in the tools repo). I would like to be more aware of why we would be having problems with this as it is something we need to tackle with all non-latin language scripts.

**Comment by richmahn** [comment]
Kind of confusing who exactly is assigned to this now, but I guess it helps for us all to be working on it. I will be trying to do some tests with just a simple file with Farsi.

**Comment by alerque** [comment]
Sorry my time at a computer is really sketchy right now. I wasn't able to look into this before getting called out. I'll try again tomorrow. And work doesn't have to be in the master branch, if it's incomplete work commiting and pushing to a user branch can at least be something to reference when the next person comes along to see what's been tried.

**Comment by alerque** [comment]
So I have working Farsi OBS builds going on now in [my `farsi` branch](https://github.com/alerque/uw-tools/commits/farsi). A draft [PDF has bee posted to Slack](https://team43.slack.com/files/caleb/F0B2JL8NS/obs-fa-v4_1.pdf). However I'm holding off on a PR because there is still one outstanding issue: I broke most of the other non English languages.

The way non-en language support was programmed before was a hack that wasn't going to work for RTL support at all, so I've been working on redoing it with proper typescript groupings. Unfortunately this will mean some adjustments to the way all languages are handled in the ConTeXt template, and I'm still working on the best way to do that.

Additionally (and this should be a new issue) there are a ton of places where strings are getting concatenated with no regard to language direction. It's going to take a lot of cleanup to get all the kinks out of Farsi and future RTLs.
