### ISSUE TITLE
Remove HTML font codes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#243]
_From @jag3773 on July 23, 2015 20:40_

The tN writers are all using the WYSIWYG editor and pasting in a large amount of HTML font code.  Please create a script to automatically find and delete this code at least once per day.  

This script should only check the en:bible:notes and en:obe namespaces. Some pages, such as https://door43.org/en/bible/home contain legitimate code. It is possible we may want to add other namespaces at a later date.

These pages show the current list of pages:  https://door43.org/en/bible/resources/code/find-font-code-notes and https://door43.org/en/bible/resources/code/find-font-code-obe.

_Copied from original issue: unfoldingWord-dev/tools#109_

**Comment by jag3773** [comment]
_From @lrsallee on July 23, 2015 21:0_

Seems straight-forward, but let me know if you have any questions. larry_sallee@wycliffeassociates.org

**Comment by jag3773** [comment]
_From @superdav42 on July 23, 2015 23:38_

@jag3773 @lrsallee I think it would make a lot more sense to fix update the editor to strip out the font codes or update docuwiki to strip them out on save. Automatically running a global search and replace seems like a bad idea.

**Comment by jag3773** [comment]
_From @lrsallee on July 24, 2015 1:37_

David,

However you solve the problem is fine with us. We only care about the end result—not code throughout the text.

Larry

From: superdav42
Reply-To: unfoldingWord-dev/tools
Date: Thursday, July 23, 2015 at 7:38 PM
To: unfoldingWord-dev/tools
Cc: Larry Sallee
Subject: Re: [tools] Remove HTML font codes (#109)

@jag3773https://github.com/jag3773 @lrsalleehttps://github.com/lrsallee I think it would make a lot more sense to fix update the editor to strip out the font codes or update docuwiki to strip them out on save. Automatically running a global search and replace seems like a bad idea.

**Comment by jag3773** [comment]
_From @alerque on July 30, 2015 5:35_

I would concur with what @superdav42 said here. One additional benefit to doing this at the editor level (as a save hook or filter of some sort) has the major advantage of catching problems as they happen rather than later. If you do this later you might mess something up that the author saved and checked and thought was done and they moved on. Who knows when you would even catch that something unexpected happened. But if you do it as part of the save process, the editor that entered content in the first place will be checking the actual final result of their work and immediately be aware if there is a problem.

**Comment by lrsallee** [comment]
So, what does that mean for us. Is someone going to work on that editor level fix?

From: Jesse Griffin
Reply-To: unfoldingWord-dev/Door43
Date: Thursday, September 17, 2015 at 2:51 PM
To: unfoldingWord-dev/Door43
Cc: Larry Sallee
Subject: Re: [Door43] Remove HTML font codes (#243)

From @alerquehttps://github.com/alerque on July 30, 2015 5:35

I would concur with what @superdav42https://github.com/superdav42 said here. One additional benefit to doing this at the editor level (as a save hook or filter of some sort) has the major advantage of catching problems as they happen rather than later. If you do this later you might mess something up that the author saved and checked and thought was done and they moved on. Who knows when you would even catch that something unexpected happened. But if you do it as part of the save process, the editor that entered content in the first place will be checking the actual final result of their work and immediately be aware if there is a problem.

**Comment by jag3773** [comment]
Yes, it is on the roadmap.

**Comment by superdav42** [comment]
@jag3773 PR https://github.com/unfoldingWord-dev/Door43/issues/255
