### ISSUE TITLE
configure the Translation plugin for every language that we have configured in the translationDatabase (see the 'Phase 1' document in translationDatabase)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#27]

**Comment by richmahn** [comment]
Putting these comments from Phil on Slack in here for reference:

Phil Hopper [12:51 PM]
If I'm reading it correctly, there is a script in the plugin to do this, https://github.com/Door43/dokuwiki-plugin-translation/blob/master/lang/getLanguageNames.php.  You can run it on your development computer and it will update the languages.txt file. (edited)

Phil Hopper [12:52 PM]
If you use the script, you may need to edit the languages.txt file and fix the name of the French language. See https://github.com/Door43/dokuwiki-plugin-translation/commit/ff46b1c63c8a0e555a32fcd9f0552666e717553f for details.

Phil Hopper [1:01 PM] 
If it's something that gets updated frequently, it may be a good idea to have the script run periodically on the server rather than having an old list in the repo.

**Comment by jag3773** [comment]
Dup #203
