### ISSUE TITLE
Need to add lang.php file to each language in /var/www/vhosts/door43.org/httpdocs/inc/lang that is RTL. See tk/lang.php as an example 

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#28]

**Comment by jag3773** [comment]
I think you are doing some work in this regard already, Phil.  This ticket may be superfluous, please close it if this is being addressed in another manner.

**Comment by phillip-hopper** [comment]
@jag3773 I'm working on getting the correct `lang` and `dir` attributes on the `html` tag, which is a prerequisite for this issue. This looks like a request to actually localize dokuwiki in more languages, which is beyond my skill set at this time.

**Comment by jag3773** [comment]
@phillip-hopper Actually, this is just so that RTL languages show up RTL in DokuWiki.  You'll notice that the only thing I put in https://github.com/unfoldingWord-dev/Door43/blob/development/inc/lang/tk/lang.php is encoding and text direction.  Eventually, that file _could_ be used for localizing the interface, but that is not on the radar for this issue.

**Comment by phillip-hopper** [comment]
@jag3773 I think what I've done resolves this issue, using the information from `https://td.unfoldingword.org/exports/langnames.json`. The "tk" language is labeled LTR in that file, but if you open both https://door43.org/arc/home and http://test.door43.org/arc/home you can see the difference.

**Comment by jag3773** [comment]
OK, as long as we are handling text direction based on the information from
tD then this issue can be closed.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
