### ISSUE TITLE
Push content from en to other languages

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#4]

**Comment by jag3773** [comment]
The need here is to take content created in the en namespace and move it into another language so that translators can start translating the content.  For instance, push pages tagged "publish" is in the en:ta namespace to sw:ta namespace.

Right now we have some scripts setup to do this, but it would be great if we could do it in a self service manner.  The door43obs plugin is already setup to do this for OBS (https://door43.org/obs-setup, and https://github.com/Door43/dokuwiki-plugin-obs).  Perhaps we want to extend this plugin?

For starters, we need to be able to copy over translationNotes and the key terms for OBS, but also for Bible, eventually.  This does something similar https://github.com/Door43/tools/blob/master/obs/dokuwiki/obs-notes-creator.sh.

**Comment by jag3773** [comment]
Clarification: we only want to be pulling content that is checked to level 3 from the uW API.  So the source text for this needs to come out of the API, not Door43.

**Comment by jag3773** [comment]
Related to #166 .

**Comment by jag3773** [comment]
Dup of #166
