### ISSUE TITLE
User Editor Choice Persistence

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Door43#58]
A user's choice of editor is not getting set correctly on Door43 (cookie problem?).

We need to create a user preference that allows users to select either the WYSIWYG editor or the DW editor as their personal default OR we need to fix the cookie/cache issue in the current editor that is preventing it from being saved.

**Comment by yvonnel098** [comment]
When I use dokuwiki, I save the text in one editor.  The next time the text load, it will use the editor I saved it at unless I go into edit mode and switch the editor.  Is this feature not working on Door43?

**Comment by jag3773** [comment]
It is not working.  What we need is a user preference where they can choose what editor they want to use and then that always persists for their user account.

**Comment by yvonnel098** [comment]
I am not familiar with dokuwiki's user set up.  Does a normal user has access to certain portion of admin?

**Comment by jag3773** [comment]
I'm talking about the profile page.  If you are logged in, click on "update
profile" in the upper right and you'll see what I mean.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by jag3773** [comment]
Yvonne, where are we at on this?  Do you have an expected time of completion?

**Comment by yvonnel098** [comment]
I wrote an syntax and action plugin that let user set the cookie for ckgedit.  I'm currently trying to upload to the test server to test it.  Rich wanted me to fork the door43 repository, add my pluin then issue a pull request.  After that, I need to use git pull to install the plugin. I'm a bit confused about that.  Anyway, I've downloaded an ssh client and was able to log into the test server.  Once I figure out how to install the plugin, it should just be a day or so to test and make sure it does what it suppose to do.  Right now, the user can toggle the editor choice within the editor.  Should I allow that?  Also, on an unrelated note, is Pandoc available on the test server?

**Comment by jag3773** [comment]
Yes, users should still be able to toggle from within the editor.  Pandoc is available.

**Comment by yvonnel098** [comment]
Hi, I'm having a tough time to recreate the problem. I tried both in the test server and door43.org.  I used Safari 8, IE 11 and Chrome 43.  It always worked.  The editor is what I chose before I logged out, close the browser and reopen the browser.  I haven't install my plugin yet.  But, if I don't see the problem in the first place, I can't tell if it is fixed.  The cookie the CKG Edit use is a session cookie called FCKG_USE.  If it is absent or set to "other", the CKG Edit will load instead of DW edit.  I am assuming that PHP session ends when an user log out.  Is that right?  I was monitoring session cookies.  None of them are wiped out even when I logged out.  This may be a browser problem.  There is some discussion on the web about the latest chrome not wiping out session cookies.  However, I've tested on IE and Safari, it is all doing the same thing.  

Could I talk with someone who had experience this problem so I could recreate it and monitor the cookies.  I want to make sure I'm fixing the right thing.

**Comment by ChrisJarka** [comment]
yvonne1098 - I would love to demonstrate :) - you will see how when I switch from NS to NS the editor goes back to the CKG editor. I'm using IE 11, Chrome and FF.http://screencast.com/t/sykEgzJLQe 
Does this help?

**Comment by ChrisJarka** [comment]
Oh, Yvonne, I'd love to talk with you too - what is a good time?

**Comment by lrsallee** [comment]
Yvonne, it usually holds for a namespace, but reverts when we switch namespaces. For example, open the editor for this page (https://door43.org/en/bible/notes/rom/07/24) and switch to DW Edit. Then open this page from the next namespace (https://door43.org/en/bible/notes/rom/08/01) and it will revert to CKG Edit.

**Comment by yvonnel098** [comment]
code posted in https://github.com/yvonnel098/setedit.  I've asked Rich to integrate it to Door43.  Hopefully this will solve the problem.

**Comment by lrsallee** [comment]
Yvonne,

Looking forward to that.

Larry

From: yvonnel098
Reply-To: unfoldingWord-dev/Door43
Date: Monday, August 3, 2015 at 11:59 AM
To: unfoldingWord-dev/Door43
Cc: Larry Sallee
Subject: Re: [Door43] User Editor Choice Persistence (#58)

code posted in https://github.com/yvonnel098/setedit. I've asked Rich to integrate it to Door43. Hopefully this will solve the problem.

**Comment by jag3773** [comment]
@richmahn where are we at on this?

**Comment by ChrisJarka** [comment]
It seems to be fixed. I have not had to constantly choose my editor for some time now.
Thank you!

**Comment by richmahn** [comment]
Yeah, it has been in production for a while now. Sorry this wasn't closed.

**Comment by jag3773** [comment]
I thought this would result in some sort of check box in the user profile that allows someone to choose what editor they prefer, but I'm not seeing that.  Am I missing something?

**Comment by yvonnel098** [comment]
No. The fix is to extend the cookies that ckg edit use to tell which editor to invoke to all namespaces. So if an user set editor choice in one namespace, he doesn't need to set it again when he switch to a different post. He could also just use the normal buttons/ link provide by ckg edit to switch editor

**Comment by yvonnel098** [comment]
This plugin may need to be updated when ckg edit is updated. I have found that different version of ckg edit use cookies differently

**Comment by jag3773** [comment]
OK, great, thanks!
