### ISSUE TITLE
 Somtimes redirects to ?doku.php[namespace], but should use normal pretty url (e.g. en/bible/notes) (WYSIWYG editor)

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/Door43#6]

**Comment by jag3773** [comment]
Is this something that we need to hack DW to enforce?  Or is there another way?

**Comment by superdav42** [comment]
@leok22 @jag3773 How can I reproduce this, when does sometimes happen? link?

**Comment by jag3773** [comment]
When editing a page with the CKG editor this will happen sometimes. I think
if you edit the page and then click on document edit it might take you to
the ? version.

**Comment by superdav42** [comment]
Problem is here the ckgedit plugin
https://github.com/turnermm/ckgedit/blob/adbf9b6f9eaa307aba5ba595d1f571309e6786cf/action/meta.php#L518
commenting out that line fixes the links so they are always pretty but breaks all image links. 
Looking at the best way to fix it.

**Comment by superdav42** [comment]
Actually I think the solution is just to fix how the "DW Edit" link is rendered. @jag3773  I forked the official ckedit repo  to my own account https://github.com/superdav42/ckgedit you can install it and all should be fixed. I didn't have access to door43 to create repos but you can move it there if you'd like.
Also made PR to get it fixed in official repo. 
https://github.com/turnermm/ckgedit/pull/97

**Comment by superdav42** [comment]
@jag3773 turnermm merged my PR into the official repo. Update the ckgedit plugin in the admin http://test.door43.org/en/home?do=admin&page=plugin and it'll be working fine.
